#!/usr/bin/env npx tsx
/**
 * protoc-gen-netclode-enums
 *
 * Custom buf plugin that generates string union types and exhaustive
 * mapping functions from protobuf enums.
 */

import { createEcmaScriptPlugin, runNodeJs, type Schema } from "@bufbuild/protoplugin";
import type { DescEnum, DescEnumValue } from "@bufbuild/protobuf";

/**
 * Find the common proto prefix shared by all enum value names.
 * E.g., for ["SDK_TYPE_CLAUDE", "SDK_TYPE_OPENCODE"] → "SDK_TYPE"
 */
function commonPrefix(names: string[]): string {
  if (names.length === 0) return "";
  let prefix = names[0];
  for (const name of names) {
    while (!name.startsWith(prefix)) {
      prefix = prefix.slice(0, -1);
    }
    if (prefix === "") break;
  }
  // Strip trailing underscore
  while (prefix.endsWith("_")) prefix = prefix.slice(0, -1);
  return prefix;
}

/**
 * Strip the common prefix and lowercase. E.g., "SDK_TYPE_CLAUDE" → "claude"
 */
function valueToUnionMember(value: DescEnumValue): string {
  return value.localName.toLowerCase();
}

/**
 * E.g., "SdkType" → "sdkType"
 */
function functionName(enumName: string): string {
  return enumName.charAt(0).toLowerCase() + enumName.slice(1);
}

const plugin = createEcmaScriptPlugin({
  name: "protoc-gen-netclode-enums",
  version: "v1.0.0",
  generateTs(schema: Schema) {
    for (const file of schema.files) {
      if (file.enums.length === 0) continue;

      const f = schema.generateFile(`${file.name}.enums.ts`);
      f.print("// @generated by protoc-gen-netclode-enums — DO NOT EDIT");
      f.print("// source:", file.name + ".proto");
      f.print();

      // Import the proto-generated enum types (sibling file in same dir)
      const importPath = `./${file.name.split("/").pop()}_pb.js`;
      f.print(`import {`);
      for (const e of file.enums) {
        f.print(`  ${e.name} as _Proto${e.name},`);
      }
      f.print(`} from "${importPath}";`);
      f.print();

      for (const enumDesc of file.enums) {
        const protoName = `_Proto${enumDesc.name}`;
        const fnName = functionName(enumDesc.name) + "FromProto";

        // All values except UNSPECIFIED (number === 0)
        const declaredValues = enumDesc.values.filter((v) => v.number !== 0);
        const unspecifiedValue = enumDesc.values.find((v) => v.number === 0);

        // Compute common prefix from all non-unspecified value names
        const defaultResult = declaredValues.length > 0
          ? valueToUnionMember(declaredValues[0])
          : "unknown";

        // String union type
        const members = declaredValues.map((v) =>
          JSON.stringify(valueToUnionMember(v)),
        );
        f.print(`export type ${enumDesc.name}Type = ${members.join(" | ")};`);

        // Exhaustive mapping function — NO default branch
        f.print(
          `export function ${fnName}(v: ${protoName} | undefined): ${enumDesc.name}Type {`,
        );
        f.print(`  switch (v) {`);
        for (const value of declaredValues) {
          const result = valueToUnionMember(value);
          f.print(`    case ${protoName}.${value.localName}: return ${JSON.stringify(result)};`);
        }
        if (unspecifiedValue) {
          f.print(
            `    case ${protoName}.${unspecifiedValue.localName}: return ${JSON.stringify(defaultResult)};`,
          );
        }
        f.print(`  }`);
        f.print(`  throw new Error(\`Unhandled ${enumDesc.name}: \${v}\`);`);
        f.print(`}`);
        f.print();
      }
    }
  },
});

runNodeJs(plugin);
